import { Unlock } from "lucide-react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import NextTopLoader from "nextjs-toploader";
import "../globals.scss";
import { Providers } from "../providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextTopLoader
          color="#9dc900"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
        />
        <Providers>
          <div className="w-full min-h-screen light bg-[#f2f2f2] dark:bg-[#2a2b2f] relative flex items-center justify-center flex-col font-inter py-10">
            <Link href="/">
              <h3 className="text-3xl">GoSolar.ng</h3>
            </Link>
            {/* <ThemeSwitcher /> */}
            <div className="auth-content p-4 mx-auto">
              <div className="w-full light bg-white dark:bg-[#222327] shadow-lg">
                <div className="flex flex-col items-center py-8 px-6">
                  <div className="mb-4 text-primary">
                    <Unlock size={30} />
                  </div>
                  <div className="w-full ">{children}</div>
                </div>
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
