import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import AuthLayout from "@/layouts/AuthLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="auth-wrapper bg-red-400 w-full h-screen">
          <div className="auth-content">
            <div className="auth-bg">
              <span className="r"></span>
              <span className="r s"></span>
              <span className="r s"></span>
              <span className="r"></span>
            </div>
            <div className="card">
              <div className="card-body text-center">
                <div className="mb-4">
                  <i className="feather icon-unlock auth-icon"></i>
                </div>
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
