import LoadingSpinner from "@/components/LoadingSpinner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import HeaderShop from "../(ecommerce)/components/shop/HeaderShop";
import "../globals.css";
import { Providers } from "../providers";
import ProfileSidebar from "./components/ProfileSidebar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextTopLoader
          color="#08AA08"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
        />
        <Providers>
          <Suspense fallback={<LoadingSpinner />}>
            <HeaderShop />
            <div className="min-h-screen bg-muted/30 dark:bg-zinc-950/40 text-foreground transition-colors duration-300 py-8">
              <div className="w-full container max-w-6xl mx-auto px-4 grid grid-cols-1 lg:grid-cols-4 gap-8">
                <div className="col-span-1">
                  <ProfileSidebar />
                </div>
                <main className="w-full lg:col-span-3 bg-card border border-border/80 shadow-xs rounded-2xl p-6 min-h-[70dvh] flex flex-col justify-between">
                  <div className="w-full">
                    {children}
                  </div>
                </main>
              </div>
            </div>
            <Footer />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
